server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/stock
    username: root
    password: root

  jpa:
    hibernate:
      host: localhost
      port: 3306
      database: stock