server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/acelerateti
    username: root
    password: Leandro2009*

  jpa:
    hibernate:
      host: localhost
      port: 3306
      database: acelerateti