spring:
  datasource:
    url: jdbc:mysql://localhost:3307/stock
    username: root
    password: Juank5680

  jpa:
    hibernate:
      host: localhost
      port: 3307
      database: stock
      ddl-auto: update
      show-sql: true